spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      password: ${REDIS_PASSWORD}

app:
  security:
    token-blacklist:
      backend: redis
  device:
    hikvision:
      mock-enabled: false
